### ISSUE TITLE
Toggle for gate/trigger doesn't change value

### ISSUE THREAD

**Issue by jjdeprisco** [Stubs42/OrangeLine#12]
For Dejavu - Clicking the toggle button to change from gate to trigger doesn't set the value. The light changes to yellow, but the value is always 0. Manually entering the desired value (0 or 1) works.

**Comment by Stubs42** [comment]
That's absolutely ok . The button is interpreted as a trigger changing its state. don't has to be set to 1 for functioning.
Regards Dieter
