### ISSUE TITLE
v2 Crash

### ISSUE THREAD

**Issue by Torinbob** [Stubs42/OrangeLine#13]
Hi Dieter,

Here's my log after the crash I get with OrangeLine installed. This happens without even having the modules connected, just had one added to the patch. It did not crash immediately on adding but shortly afterwards. Crash occurs within first minute or two of starting Rack.

<img width="694" alt="Screenshot 2021-10-08 at 11 53 31" src="https://user-images.githubusercontent.com/41232273/136550008-cbc88c4b-02f5-4341-95e6-2a9b0ec18b4c.png">

**Comment by Stubs42** [comment]
should be fixed now
