### ISSUE TITLE
Fence does not do anything until it's "drawn"

### ISSUE THREAD

**Issue by Petervos2018** [Stubs42/OrangeLine#15]
Hi Dieter

When you open a project that is zoomed in so you don't see Fence (it's off-screen) it won't do anything until you zoom out or pan so that you can "see" the module (on-screen).

If you need more info or an example project let me know.

Greeting Peter.

Windows 10, VCV free v2

**Comment by Stubs42** [comment]
Just tried that and could not reproduce this behaviour. Can you send a patch where this happens ?

**Comment by Petervos2018** [comment]
Here it is : 
[Fence.zip](https://github.com/Stubs42/OrangeLine/files/7735230/Fence.zip)

Zoom in until you only see Four view, 1 is S&H, 2 is S&H after Fence.
Close rack , reopen and you'll see that four-view 2 is C4 and it stays that way until you zoom out.

Fun fact, when I remove mix-8 from NYSTHI it does not happen.....

**Comment by Stubs42** [comment]
Just checked and found out that when yoru audio is connected to valid sound output everything works fine.
even switching the color theme of fence does not work when there is no audio processing going on. Looks like v2 just doesnt call the process method when there is no audio is to generate.

**Comment by Stubs42** [comment]
Thanks for your patch. I can now reproduce the behavior you described. I think this is maybe a bug of v2.
It looks like that v2 is not creating the module widget until it has to be drawn. So to avoid crashed my modules do nothing until the widget hast been instantiated. If this is the expected behavior of v2, I'll have to think about another solution for this problem.

**Comment by Petervos2018** [comment]
Hi Dieter,

thanks for investigating, as I said it's not really a bug because I stumbled upon it doing something weird, but it is nice to know that you can reproduce it.

Greetings Peter.

**Comment by Stubs42** [comment]
Just uploaded a prerelease at:
https://github.com/Stubs42/OrangeLine/releases/download/2.3.10/OrangeLine-2.3.10-win.vcvplugin
Should fix the problem. Let me know whether you encounter any problems with the fix

**Comment by Petervos2018** [comment]
Works 👍

**Comment by Stubs42** [comment]
thanks for finding this
