### ISSUE TITLE
Crash when connecting DejaVu's Rep out to mother's root in

### ISSUE THREAD

**Issue by lsf3og** [Stubs42/OrangeLine#17]
I had a crash when connecting DejaVu's Rep out to mother's root in. This happened when VCV was running as VST in Ableton.
These are the last two lines of an ableton log that seem to correspond to the issue:

2021-12-22T07:59:31.989029=status {"audio_drop_outs":"0","audio_usage_average":"41.1275","audio_usage_peak":"49.575","mem_private":"1859858432","mem_resident":"1476288512","mem_virtual":"7533592576"}
2021-12-22T08:00:43.941123=abort {"mem_private":"1856290816","mem_resident":"1478152192","mem_virtual":"7535132672","message":"Fatal error: the audio engine is not responding."}

I also attached a screenshot (sorry, for the bad quality - Live was unresponsive).

![Screenshot 2021-12-22 085617](https://user-images.githubusercontent.com/29233639/147056467-022d2fed-cf78-4bc5-8798-9c60e5328993.jpg)

**Comment by Stubs42** [comment]
Hi,
Connecting the rep out to the root of mother doesn't make sense in any way but you are right that there should be a crash because of this. I will have look at it.

**Comment by Stubs42** [comment]
Hi,
Just checked it and could not reproduce it on my system. 
What do you feed into the rep and trg inputs ?
Just submitted OrangeLine 2.3.11 to the plugin manager. Added some clamping on the inputs.
Hopefully this will fix this.
But anyway. The rep and trg inputs 'experimantal' and until now I found now real use case for them.
So maybe I will remove them in future releases at all.
