### ISSUE TITLE
Range scrolling bug/glitch

### ISSUE THREAD

**Issue by pgatt** [Stubs42/OrangeLine#2]
Hi Dieter,

When selecting the frequency range and scrolling through the notes, it isn't (at least visually) always scrolling correctly when changing octave at C. In order it is possible to select B5, C5 and then C6. I would have expected C5 to not be between B5 and C6.

Thanks for the plugin - using it right now!

**Comment by Stubs42** [comment]
Fixed :-)

**Comment by Stubs42** [comment]
Didn't update the release zips because its a minor issue, so you have to build from src if you want this early.
