### ISSUE TITLE
Step / Fallback value loads incorrectly

### ISSUE THREAD

**Issue by strangebuttrue** [Stubs42/OrangeLine#21]
I save a patch with Fence's Step / Fallback set to 1v, then close the patch and load it again, and the Step/Fallback value is now 0.917. This sends my pitches out of tune, and surely isn't the intended behavior of this module? I like Fence a lot, and if I have to manually reset this knob to 1v every time I use it I will, but this sounds like a bug......

![fence issue](https://user-images.githubusercontent.com/76659301/208685253-7f922615-1980-4611-b5c2-00eceda48d0e.png)

**Comment by Stubs42** [comment]
Hello,
This is strange. I could reproduce the error. The strange thing is that when I create a preset with STEP 1 V and load the the preset, STEP is set correctly to 1V. I always thought there is no difference between the preset data and the data stored for a module in the patch. Have to further investigate when I can find some time for it.
Regards
Dieter

**Comment by strangebuttrue** [comment]
Thank you! The modules are great, overall! The workaround I use for this
is...... I connect it to a consistent source of 1 volt at the STEP input
