### ISSUE TITLE
MOTHER: Copy scale option?

### ISSUE THREAD

**Issue by bram2000** [Stubs42/OrangeLine#24]
Hi, In MOTHER, is there any way to copy the current scale and probabilities to another scale position? I'd like to setup an initial idea then evolve it across the difference scales (as you did in the video you made with the Frozen Wasteland modules).

Cheers!

**Comment by Stubs42** [comment]
Hi,
Currently the is no way to copy scales or child scale weights between scales. I'll take you issus as a feature request and I am thinking on adding some right click options to copy paste between scales.

**Comment by Stubs42** [comment]
Just released 2.4.5 to the library. will take some days to apear in the lib.
MOTHER now can copy paste whole scales including all child weights or just the weights of single child.
