### ISSUE TITLE
Morph/Morpheus crashing vcv

### ISSUE THREAD

**Issue by mizi0** [Stubs42/OrangeLine#26]
I really like this modules, however they crash vcv everytime: morpheus as soon i connect a clock and start generating notes, morph let me work and generate sequences successfully, but when i quit vcv/save patch, it crash.

Intel i5 12600kf, 32gbddr5, win 10pro 22h2, vcv pro 2.4.1

**Comment by Stubs42** [comment]
Hi,
working with MORPHEUS quite some time now and did not have any issues.
Can you send me a patch or a more detailed discription when this is happening.?
Please also provide the vcv logfile after vcv crashed.

**Comment by mizi0** [comment]
This happened, as i stated in my previous message, when i added Morpheus to my patch, connected clk, then closed vcv.
On re-opening it is not able to reload the patch and vcv crash.
[log.txt](https://github.com/Stubs42/OrangeLine/files/14421840/log.txt)

next i will send experiment with Morph

**Comment by Stubs42** [comment]
Cannot reproduce this. Can you send me the vcv logfile after it crashes please?

**Comment by Stubs42** [comment]
Can you send me the patch before you add MORPHEUS?
Maybe I can reproduce it this way.

**Comment by mizi0** [comment]
This is my template patch, i start with it then add morpheus, connect it to clk then i shut down vcv, on restarting the program, it crash, not being able to re-load the patch and the only way to restart rack is clearing the patch(asked from vcv on launch).

[patch.rar.txt](https://github.com/Stubs42/OrangeLine/files/14431912/patch.rar.txt)

just save the file and rename deleting .txt (can't send .vcv files on this chat)
I also added the log file, as in my previous message.
Thanks for your support

**Comment by Stubs42** [comment]
Found the problem and fixed it for MORPHEUS. The problem was that the mem slot number display widget might not have been created wenn process is called the first time. Did you had a problem with MORPH too?
Before releasing the fix to the library I would like to fix that also

**Comment by Stubs42** [comment]
Just released the fix. Just wait for 2.4.5 popping up in the library.

**Comment by mizi0** [comment]
I am very happy you found the problem, can't wait to try in my patches!
Yes i had problems with morph too, i have tried to replicate the bug but so far i was not able, will try again and send patch+log if i succeed.
I remember tough, the behaviour was similar, and i suspect the internal structure of the 2 modules is similar too, maybe an analogous bug? (sorry if this in not helping,just a suggestion i am not a programmer by any means...)

**Comment by Stubs42** [comment]
The problem with MORPHEUS was that process() is already called by Rack before the widgets are created. MORPHEUS  access ed the MEM display widget (displaying the memory slot number) before it was created, causing the crash. Now it checks whether the widget has been created yet to avoid that. MORPH does not have this display. So if there is a problem with MORPH it would be something different. Reopen the issue if you can reproduce the problem with MORPH.
