### ISSUE TITLE
Morpheus poly LEN input question

### ISSUE THREAD

**Issue by paulrobertpine** [Stubs42/OrangeLine#27]
Hi there, 

I'm not sure what I'm doing wrong or maybe it's an issue. Using Polycon8 from BOGaudio as a constant voltage source, I can't get the sequence length to be consistant using the LEN input oh Morpheus. For example using a set value of 0.05 will still produce a 4-step sequence. It seems to favour the even-numbered sequences. Any advice much appreciated. 

![morpheus-LEN](https://github.com/Stubs42/OrangeLine/assets/33700095/2cf45fda-499a-4b39-ab80-3d7225d70315)

**Comment by Stubs42** [comment]
Hi,
Good find. Checked that and can reproduce it. POLYCON8 sending 0.05V will result in a 4 step sequence but also checked with the Specific Value module and 0.05V will produce a 5 step sequence. I assume that POLYCON8 is giving something like 0.0499999... which might get floored to 0.04. setting POLYCON8 to 0.051 will produce a correct 5 step sequence.
I will check that and use some rounding when reading cv from the LEN input. For the moment just add 0.001 to your length CVs and will work.
Hope that helps.

**Comment by Stubs42** [comment]
Just had a look in the code and fixed it.
Will be fixed with next release in library.
