### ISSUE TITLE
plugin.json issues

### ISSUE THREAD

**Issue by cschol** [Stubs42/OrangeLine#3]
```
Fence: invalid module tags: Distorsion
Fence: module slug flagged
-- Valid tags are defined in https://raw.githubusercontent.com/VCVRack/Rack/v1/src/tag.cpp
Invalid license ID: AGPL
-- License must be a valid Identifier from https://spdx.org/licenses/
```

**Comment by Stubs42** [comment]
Hi,
just changed licensing to GPLv3 and added license headers to src files.
removed the tag Distorsion.
Hopefully everything is fine now, let me know.

**Comment by Stubs42** [comment]
Hi,
just changed licensing to GPLv3 and added license headers to src files.
removed the tag Distorsion.
Hopefully everything is fine now, let me know.
Make sure you use version 1.0.0 of branch 1.0.0

**Comment by Stubs42** [comment]
Sry did not want to close this

**Comment by cschol** [comment]
One more issue in `plugin.json`:

```
Invalid license ID: GPLv3
-- License must be a valid Identifier from https://spdx.org/licenses/
```

The ID must match a valid ID from the site.

**Comment by Stubs42** [comment]
fixed it to GPL-3.0-only
hope this is ok now.

**Comment by cschol** [comment]
Everything is OK now. Thanks.

**Comment by Stubs42** [comment]
Hi,
just realized that the plugin manager now contains the wrong version of orange line.
All changes to fix above issues were made in branch 1.0.0 of OrangeLine.
Now you release the branch master which is work in progress and is not stable.
Please make sure your build the OrangeLine pluging from Branch 1.0.0.
Hope this will be solved fast because I do not want to look bad with my first release.

**Comment by cschol** [comment]
Ugh, that was my mistake. I apologize. I asked Andrew to pull the current plugin version and I will fix the commit for the next build update.

**Comment by cschol** [comment]
Correct version of the plugin is in the Plugin Manager now. I apologize again for the mishap.

**Comment by Stubs42** [comment]
Thx, for solving this. Don't mind. Shit happens ;-)
